#! /bin/bash
sudo yum -y update
sudo amazon-linux-extras install -y nginx1
ipv4=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
echo "Hello from ${ipv4}" > /usr/share/nginx/html/site.html
sudo service nginx start
