#! /bin/bash
sudo yum -y update
sudo amazon-linux-extras install -y nginx1
sudo service nginx start
sudo yum install -y python python-setuptools python-dev build-essential python-pip python-mysqldb git
sudo pip install flask
FLASK_APP=app.py flask run --host=0.0.0.0
